all:
	# gcc -iquote "lib" src/1.c ./lib/*.c -fno-strict-aliasing -lm -o ./1.out -g
	# gcc -iquote "lib" src/2.c ./lib/*.c -fno-strict-aliasing -lm -o ./2.out
	# gcc -iquote "lib" src/3.c ./lib/*.c -fno-strict-aliasing -lm -o ./3.out
	# gcc -iquote "lib" src/4.c ./lib/*.c -fno-strict-aliasing -lm -o ./4.out
	# gcc -iquote "lib" src/5.c ./lib/*.c -fno-strict-aliasing -lm -o ./5.out
	# gcc -iquote "lib" src/6.c ./lib/*.c -fno-strict-aliasing -lm -o ./6.out -g
	# gcc -iquote "lib" src/7.c ./lib/*.c -fno-strict-aliasing -lm -o ./7.out
	# gcc -iquote "lib" src/8.c ./lib/*.c -fno-strict-aliasing -lm -o ./8.out
	gcc -iquote "lib" src/9.c ./lib/*.c -fno-strict-aliasing -lm -o ./9.out
	# gcc -iquote "lib" src/10.c ./lib/*.c -fno-strict-aliasing -lm -o ./10.out